change-template: '- $TITLE (@$AUTHOR, PR #$NUMBER)'
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    collapse-after: 5
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    collapse-after: 5
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    collapse-after: 5
    label: 'chore'
exclude-contributors:
  - 'action-user'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
