name: Monorepo split

on:
  workflow_call:
    inputs:
      organization:
        description: 'Org'
        required: true
        type: string
      package:
        description: 'Package'
        required: true
        type: string
    secrets:
      gh-token:
        required: true
jobs:
  split-branch:
    name: Split branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.gh-token }}

      - run: git config --global user.name "GitHub Action"
      - run: git config --global user.email "action@github.com"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Split
        uses: "AloisJasa/.github/.github/actions/split-monorepo@main"
        with:
          organization: "${{ inputs.organization }}"
          package: "${{ inputs.package }}"
          gh-token: "${{ secrets.gh-token }}"
