name: Monorepo split

on:
  workflow_dispatch:
    inputs:
      organization:
        description: 'Org'
        required: true
        type: string
      package:
        description: 'Package'
        required: true
        type: string
    secrets:
      gh-token:
        required: true
jobs:
  split-branch:
    name: Split branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.gh-token }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git-filter-repo

      - name: Split
        run: |
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          bash ./.github/scripts/split-repositories.sh "${{ inputs.package }}" ${{ inputs.organization }} "${{ github.ref_name }}"
